import type { Property } from "@/types/property";

export const properties: Property[] = [
  {
    id: "modern-apartment-elahiyeh",
    title: "آپارتمان مدرن با تراس سبز در الهیه",
    city: "تهران",
    district: "الهیه",
    price: 42000000000,
    currency: "تومان",
    area: 185,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    propertyType: "apartment",
    status: "sale",
    imageUrl: "/placeholders/property-apartment.svg",
    gallery: [
      "/placeholders/interior-living.svg",
      "/placeholders/gallery-room.svg",
      "/placeholders/property-apartment.svg",
    ],
    description:
      "واحدی روشن و خوش‌نقشه با متریال ممتاز، آشپزخانه مجهز، تراس قابل استفاده و دسترسی سریع به خیابان‌های اصلی شمال تهران.",
    features: ["لابی اختصاصی", "تراس قابل چیدمان", "آشپزخانه مجهز", "نگهبانی ۲۴ ساعته"],
    featured: true,
    agentName: "نیلوفر امینی",
    agentPhone: "۰۹۱۲ ۴۴۰ ۱۸۷۵",
  },
  {
    id: "family-villa-shahrak-gharb",
    title: "ویلای خانوادگی بازسازی‌شده در شهرک غرب",
    city: "تهران",
    district: "شهرک غرب",
    price: 68500000000,
    currency: "تومان",
    area: 320,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 3,
    propertyType: "villa",
    status: "sale",
    imageUrl: "/placeholders/property-villa.svg",
    gallery: [
      "/placeholders/interior-living.svg",
      "/placeholders/gallery-room.svg",
      "/placeholders/property-villa.svg",
    ],
    description:
      "ویلایی کم‌نظیر با حیاط خصوصی، نورگیری عالی، فضای پذیرایی بزرگ و طراحی داخلی آرام برای زندگی خانوادگی بلندمدت.",
    features: ["حیاط خصوصی", "اتاق مستر", "بازسازی کامل", "سیستم سرمایش مرکزی"],
    featured: true,
    agentName: "کاوه رضایی",
    agentPhone: "۰۹۱۲ ۷۱۸ ۳۰۶۰",
  },
  {
    id: "tabriz-office-valiasr",
    title: "دفتر کار لوکس در ولیعصر تبریز",
    city: "تبریز",
    district: "ولیعصر",
    price: 14500000000,
    currency: "تومان",
    area: 95,
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 1,
    propertyType: "office",
    status: "sale",
    imageUrl: "/placeholders/property-office.svg",
    gallery: [
      "/placeholders/gallery-room.svg",
      "/placeholders/interior-living.svg",
      "/placeholders/property-office.svg",
    ],
    description:
      "فضای اداری خوش‌دسترسی با پلان منعطف، مناسب شرکت‌های مشاوره، فناوری و دفاتر حرفه‌ای در یکی از بهترین محدوده‌های تبریز.",
    features: ["پلان منعطف", "اتاق جلسه", "دسترسی آسان", "آسانسور اختصاصی"],
    featured: true,
    agentName: "سینا موسوی",
    agentPhone: "۰۹۱۴ ۲۲۰ ۵۷۳۱",
  },
  {
    id: "kish-sea-view-apartment",
    title: "آپارتمان چشم‌انداز دریا در کیش",
    city: "کیش",
    district: "مرجان",
    price: 28500000000,
    currency: "تومان",
    area: 138,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    propertyType: "apartment",
    status: "sale",
    imageUrl: "/placeholders/property-apartment.svg",
    gallery: [
      "/placeholders/interior-living.svg",
      "/placeholders/gallery-room.svg",
      "/placeholders/property-apartment.svg",
    ],
    description:
      "واحدی آرام با دید باز، لابی حرفه‌ای، امکانات رفاهی کامل و فاصله کوتاه تا مراکز خرید و مسیر ساحلی.",
    features: ["چشم‌انداز دریا", "لابی هتلینگ", "استخر مجموعه", "بالکن عریض"],
    featured: false,
    agentName: "رها نادری",
    agentPhone: "۰۹۳۶ ۸۸۰ ۱۱۲۴",
  },
  {
    id: "rasht-garden-villa",
    title: "باغ‌ویلا با معماری معاصر در رشت",
    city: "رشت",
    district: "گلسار",
    price: 31500000000,
    currency: "تومان",
    area: 410,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 4,
    propertyType: "villa",
    status: "sale",
    imageUrl: "/placeholders/property-villa.svg",
    gallery: [
      "/placeholders/interior-living.svg",
      "/placeholders/gallery-room.svg",
      "/placeholders/property-villa.svg",
    ],
    description:
      "باغ‌ویلایی دنج با محوطه‌سازی حرفه‌ای، فضای نشیمن باز و طراحی مناسب برای سکونت دائم یا اقامت آخر هفته.",
    features: ["محوطه‌سازی", "آلاچیق", "پنجره‌های قدی", "پارکینگ مهمان"],
    featured: false,
    agentName: "امیرحسین بهرامی",
    agentPhone: "۰۹۱۱ ۴۰۲ ۹۶۸۰",
  },
  {
    id: "isfahan-classic-apartment",
    title: "آپارتمان کلاسیک نزدیک چهارباغ اصفهان",
    city: "اصفهان",
    district: "چهارباغ بالا",
    price: 19800000000,
    currency: "تومان",
    area: 122,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    propertyType: "apartment",
    status: "sale",
    imageUrl: "/placeholders/property-apartment.svg",
    gallery: [
      "/placeholders/interior-living.svg",
      "/placeholders/gallery-room.svg",
      "/placeholders/property-apartment.svg",
    ],
    description:
      "واحدی تمیز و آماده سکونت با دسترسی عالی به مرکز شهر، مناسب خانواده‌هایی که ترکیب اصالت و امکانات شهری را می‌خواهند.",
    features: ["نورگیری عالی", "کابینت مدرن", "انباری", "دسترسی شهری"],
    featured: false,
    agentName: "ماندانا کریمی",
    agentPhone: "۰۹۱۳ ۵۰۱ ۶۴۲۲",
  },
];

export const featuredProperties = properties.filter((property) => property.featured);

export const latestProperties = properties.slice(3);

export function getPropertyById(id: string) {
  return properties.find((property) => property.id === id);
}
